colorscheme xorium
set guifont=Inconsolata:h16.00
set autoread
set gcr=n:blinkon0

if has("gui_macvim")
  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert

  " Command-Shift-F for Ack
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<nop>
  map <D-F> :Ack<space>

  " Command-/ to toggle comments
  map <D-/> <plug>NERDCommenterToggle<CR>

  " tab navigation
  map <M-D-Right> :tabnext<CR>
  map <M-D-Left> :tabprev<CR>
endif
